version: '3'
services:
  postgres:
    image: 'postgres:alpine'
  redis:
    image: 'redis:alpine'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
